### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yawhide** [diamondio/better-queue#5]
```
16:43:15 post /api/auth/authorize? 200 2347.502 ms
16:43:15 info { status: 'cancelled' } (sync.js:213)
16:43:15 err! [console] 
  printErrorAndExit [console] (source-map-support.js:366)
    at Console.error (/Users/yawhide/workspace/diamond/baymax/src/utils/log.js:141:22)
    at printErrorAndExit (/Users/yawhide/workspace/diamond/baymax/node_modules/longjohn/node_modules/source-map-support/source-map-support.js:366:13)
    at process.emit (/Users/yawhide/workspace/diamond/baymax/node_modules/longjohn/node_modules/source-map-support/source-map-support.js:383:16)
    at process._fatalException (node.js:219:26)
16:43:15 err! [console] /usr/local/lib/node_modules/better-queue/lib/queue.js:277
    var tickets = self._writing[taskId].tickets;
                                       ^
  printErrorAndExit [console] (source-map-support.js:367)
    at Console.error (/Users/yawhide/workspace/diamond/baymax/src/utils/log.js:141:22)
    at printErrorAndExit (/Users/yawhide/workspace/diamond/baymax/node_modules/longjohn/node_modules/source-map-support/source-map-support.js:367:13)
    at process.emit (/Users/yawhide/workspace/diamond/baymax/node_modules/longjohn/node_modules/source-map-support/source-map-support.js:383:16)
    at process._fatalException (node.js:219:26)
16:43:15 err! [console] TypeError: Cannot read property 'tickets' of undefined
    at Statement.<anonymous> (/usr/local/lib/node_modules/better-queue/lib/queue.js:277:40)
  printErrorAndExit [console] (source-map-support.js:370)
    at Console.error (/Users/yawhide/workspace/diamond/baymax/src/utils/log.js:141:22)
    at printErrorAndExit (/Users/yawhide/workspace/diamond/baymax/node_modules/longjohn/node_modules/source-map-support/source-map-support.js:370:11)
    at process.emit (/Users/yawhide/workspace/diamond/baymax/node_modules/longjohn/node_modules/source-map-support/source-map-support.js:383:16)
    at process._fatalException (node.js:219:26)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by leanderlee** [comment]
Do you have a test case for how to reproduce?
